// lib/widgets/vocabot/language_data.dart
// Dil veri sabitleri: desteklenen diller, bayrak eşleşmeleri ve karşılama mesajları.

// Desteklenen diller (öğrenilecek dil seçenekleri)
const Map<String, String> supportedLanguages = {
  'en': 'English',
  'es': 'Spanish',
  'de': 'German',
  'fr': 'French',
  'tr': 'Turkish',
  'it': 'Italian',
  'pt': 'Portuguese',
  // New languages
  'ar': 'Arabic',
  'ru': 'Russian',
  'ja': 'Japanese',
  'ko': 'Korean',
  'zh': 'Chinese',
  'nl': 'Dutch',
  'sv': 'Swedish',
  // Yeni eklenenler
  'pl': 'Polish',
  'el': 'Greek',
  'hu': 'Hungarian',
  'cs': 'Czech',
  'da': 'Danish',
  'fi': 'Finnish',
  'no': 'Norwegian',
  'th': 'Thai',
  'hi': 'Hindi',
  'id': 'Indonesian',
  'vi': 'Vietnamese',
  'uk': 'Ukrainian',
  'ro': 'Romanian',
  // Yeni eklenen genişletilmiş set
  'bg': 'Bulgarian',
  'hr': 'Croatian',
  'sr': 'Serbian',
  'sk': 'Slovak',
  'sl': 'Slovenian',
  'fa': 'Persian',
  'ms': 'Malay',
  'tl': 'Filipino',
  'bn': 'Bengali',
  'ur': 'Urdu',
  'sw': 'Swahili',
  'af': 'Afrikaans',
  'et': 'Estonian',
  'lt': 'Lithuanian',
  'lv': 'Latvian',
  // Ek genişletme
  'ga': 'Irish',
  'sq': 'Albanian',
  'bs': 'Bosnian',
  'mk': 'Macedonian',
  'az': 'Azerbaijani',
  'ka': 'Georgian',
  'am': 'Amharic',
  'kk': 'Kazakh',
  'mn': 'Mongolian',
  'ne': 'Nepali',
  'ta': 'Tamil',
  'te': 'Telugu',
  'gu': 'Gujarati',
  'mr': 'Marathi',
  'kn': 'Kannada',
  'si': 'Sinhala',
  // Değer katan eklemeler (ML Kit destekli)
  'ca': 'Catalan',
  'gl': 'Galician',
  'be': 'Belarusian',
  'is': 'Icelandic',
  'mt': 'Maltese',
  // Kolay bayraklı yeni eklenenler
  'pa': 'Punjabi',
  'ml': 'Malayalam',
  'or': 'Odia',
  'as': 'Assamese',
  'km': 'Khmer',
  'my': 'Burmese',
  'lo': 'Lao',
  'eu': 'Basque',
  'hy': 'Armenian',
  'cy': 'Welsh',
  'uz': 'Uzbek',
  'ps': 'Pashto',
  'ha': 'Hausa',
  'yo': 'Yoruba',
  'ig': 'Igbo',
  'so': 'Somali',
  'zu': 'Zulu',
  'xh': 'Xhosa',
  'tg': 'Tajik',
  'tk': 'Turkmen',
  'ky': 'Kyrgyz',
  // Newly added languages
  'yue': 'Cantonese',
  'eo': 'Esperanto',
  'ht': 'Haitian Creole',
  // Newly added (user request)
  'mi': 'Maori',
  'gn': 'Guarani',
  'qu': 'Quechua',
  'om': 'Oromo',
  'mg': 'Malagasy',
  'rw': 'Kinyarwanda',
  'rn': 'Kirundi',
  'sn': 'Shona',
  'tn': 'Tswana',
  'dz': 'Dzongkha',
  'jv': 'Javanese',
  'gd': 'Scottish Gaelic',
  'me': 'Montenegrin',
};

// Dil kodları ile bayrak kodları eşleştirmesi
const Map<String, String> languageFlags = {
  'en': 'gb',
  'es': 'es',
  'de': 'de',
  'fr': 'fr',
  'tr': 'tr',
  'it': 'it',
  'pt': 'pt',
  // New flags
  'ar': 'sa',
  'ru': 'ru',
  'ja': 'jp',
  'ko': 'kr',
  'zh': 'cn',
  'nl': 'nl',
  'sv': 'se',
  // Yeni eklenenler
  'pl': 'pl',
  'el': 'gr',
  'hu': 'hu',
  'cs': 'cz',
  'da': 'dk',
  'fi': 'fi',
  'no': 'no',
  'th': 'th',
  'hi': 'in',
  'id': 'id',
  'vi': 'vn',
  'uk': 'ua',
  'ro': 'ro',
  // Yeni eklenenler
  'bg': 'bg',
  'hr': 'hr',
  'sr': 'rs',
  'sk': 'sk',
  'sl': 'si',
  'fa': 'ir',
  'ms': 'my',
  'tl': 'ph',
  'bn': 'bd',
  'ur': 'pk',
  'sw': 'ke',
  'af': 'za',
  'et': 'ee',
  'lt': 'lt',
  'lv': 'lv',
  // Ek genişletme (doğru bayrak eşleşmeleri)
  'ga': 'ie',
  'sq': 'al',
  'bs': 'ba',
  'mk': 'mk',
  'az': 'az',
  'ka': 'ge',
  'am': 'et',
  'kk': 'kz',
  'mn': 'mn',
  'ne': 'np',
  'ta': 'in',
  'te': 'in',
  'gu': 'in',
  'mr': 'in',
  'kn': 'in',
  'si': 'lk',
  // Eklenenler
  'ca': 'ad',
  'gl': 'es',
  'be': 'by',
  'is': 'is',
  'mt': 'mt',
  // Yeni eklenenler (kolay bayrak)
  'pa': 'in',
  'ml': 'in',
  'or': 'in',
  'as': 'in',
  'km': 'kh',
  'my': 'mm',
  'lo': 'la',
  'eu': 'es',
  'hy': 'am',
  'cy': 'gb',
  'uz': 'uz',
  'ps': 'af',
  'ha': 'ng',
  'yo': 'ng',
  'ig': 'ng',
  'so': 'so',
  'zu': 'za',
  'xh': 'za',
  'tg': 'tj',
  'tk': 'tm',
  'ky': 'kg',
  // Newly added flags
  'yue': 'hk',
  'eo': 'un',
  'ht': 'ht',
  // Newly added flags (user request)
  'mi': 'nz',
  'gn': 'py',
  'qu': 'pe',
  'om': 'et',
  'mg': 'mg',
  'rw': 'rw',
  'rn': 'bi',
  'sn': 'zw',
  'tn': 'bw',
  'dz': 'bt',
  'jv': 'id',
  'gd': 'gb-sct',
  'me': 'me',
};

// Açılış selamları (hedef öğrenilen dilde)
const Map<String, String> welcomeMessages = {
  'en': 'Welcome back to the language universe. Ready to push your limits?',
  'es': 'Bienvenido de nuevo al universo de los idiomas. ¿Listo para superarte?',
  'de': 'Willkommen zurück im Sprachen-Universum. Bereit, deine Grenzen zu pushen?',
  'fr': 'Bon retour dans l’univers des langues. Prêt(e) à repousser tes limites?',
  'tr': 'Dil evrenine tekrar hoş geldin. Sınırlarını zorlamaya hazır mısın?',
  'it': 'Bentornato nell\'universo delle lingue. Pronto a superare i tuoi limiti?',
  'pt': 'Bem-vindo de volta ao universo dos idiomas. Pronto para ir além?',
  // New language welcomes
  'ar': 'مرحبًا بعودتك إلى كون اللغات. هل أنت مستعد لتتحدى حدودك؟',
  'ru': 'С возвращением во вселенную языков. Готов расширять свои границы?',
  'ja': '言語の宇宙へようこそ。限界に挑戦する準備はできた？',
  'ko': '언어의 우주에 다시 온 걸 환영해. 한계를 넘어볼 준비 됐어?',
  'zh': '欢迎回到语言宇宙。准备好挑战你的极限了吗？',
  'nl': 'Welkom terug in het taaluniversum. Klaar om je grenzen te verleggen?',
  'sv': 'Välkommen tillbaka till språkets universum. Redo att tänja på dina gränser?',
  // Yeni eklenenler
  'pl': 'Witaj ponownie w językowym uniwersum. Gotowy na wyzwanie?',
  'el': 'Καλώς επέστρεψες στο σύμπαν των γλωσσών. Έτοιμος για πρόκληση;',
  'hu': 'Üdv újra a nyelvi univerzumban. Készen állsz a kihívásra?',
  'cs': 'Vítej zpět ve vesmíru jazyků. Připraven posunout své limity?',
  'da': 'Velkommen tilbage til sproguniverset. Klar til at presse dine grænser?',
  'fi': 'Tervetuloa takaisin kieliuniversumiin. Valmis haastamaan rajasi?',
  'no': 'Velkommen tilbake til språkuniverset. Klar til å presse grensene dine?',
  'th': 'ยินดีต้อนรับกลับสู่จักรวาลภาษา พร้อมท้าทายขีดจำกัดไหม?',
  'hi': 'भाषा ब्रह्मांड में फिर स्वागत है। तैयार हो अपनी सीमाएँ बढ���ाने के लिए?',
  'id': 'Selamat datang kembali di jagat bahasa. Siap menantang batasmu?',
  'vi': 'Chào mừng trở lại vũ trụ ngôn ngữ. Sẵn sàng thử thách giới hạn chứ?',
  'uk': 'Ласкаво просимо назад у мовний всесвіт. Готовий розширювати межі?',
  'ro': 'Bine ai revenit în universul limbilor. Gata să îți depășești limitele?',
  // Yeni eklenen genişletilmiş set
  'bg': 'Добре дошъл отново в езиковата вселена. Готов ли си?',
  'hr': 'Dobrodošao natrag u svemir jezika. Spreman?',
  'sr': 'Добро вратио си се у језички универзум. Спреман?',
  'sk': 'Vitaj späť vo vesmíre jazykov. Pripravený?',
  'sl': 'Dobrodošel nazaj v jezikovnem vesolju. Pripravljen?',
  'fa': 'به دنیای زبان‌ها برگشتی، آماده‌ای خودت را به چالش بکشی؟',
  'ms': 'Selamat kembali ke alam bahasa. Sedia cabar diri?',
  'tl': 'Balik ka na sa uniberso ng wika. Handa ka na ba?',
  'bn': 'ভাষার মহাবিশ্বে আবার স্বাগতম। প্রস্তুত তো?',
  'ur': 'زبانوں کی کائنات میں واپسی پر خوش آمدید، تیار ہو؟',
  'sw': 'Karibu tena kwenye ulimwengu wa lugha. Uko tayari?',
  'af': 'Welkom terug in die taalheelal. Gereed?',
  'et': 'Tere tulemast tagasi keelte universumisse. Valmis?',
  'lt': 'Sveikas sugrįžęs į kalbų visatą. Pasiruošęs?',
  'lv': 'Laipni lūdzam atpakaļ valodu visumā. Gatavs?',
  // Ek genişletme
  'ga': 'Fáilte ar ais chuig cruinne na dteangacha. Réidh?',
  'sq': 'Mirë se u ktheve në universin e gjuhëve. Gati?',
  'bs': 'Dobrodošao nazad u svemir jezika. Spreman?',
  'mk': 'Добредојде назад во јазичната вселена. Подготвен?',
  'az': 'Dil kainatına yenidən xoş gəldin. Hazırsan?',
  'ka': 'კეთილი იყოს შენი დაბრუნება ენების სამყაროში. მზად ხარ?',
  'am': 'እንኳን ወደ ቋንቋዎች አለም በደህና መጣህ። ዝግጁ ነህ?',
  'kk': 'Тілдер әлеміне қайта қош келдің. Дайынсың ба?',
  'mn': 'Хэлний ертөнцөд дахин тавтай морил. Бэлэн үү?',
  'ne': 'भाषा ब्रह्माण्डमा फेरि स्वागत छ। तयार?',
  'ta': 'மொழி பிரபஞ்சத்திற்கு மறுபடியும் வரவேற்கிறேன். தயார்?',
  'te': 'భాషా విశ్వానికి తిరిగి స్వాగతం. సిద్ధమేనా?',
  'gu': 'ભાષા બ્રહ્માંડમાં ફરી સ્વાગત. તૈયાર?',
  'mr': 'भाषा विश्वात परत स्वागत. तयार?',
  'kn': 'ಭಾಷಾ ಬ್ರಹ್ಮಾಂಡಕ್ಕೆ ಮರಳಿ ಸುಸ್ವಾಗತ. ಸಿದ್ಧವಾ?',
  'si': 'භාෂා බ්‍රහ්මාණ්ඩයට නැවත සාදරයෙන් පිළිගන්නවා. සූදානම්ද?',
  // Yeni eklenenler
  'ca': 'Benvingut de nou a l\'univers de les llengües. Preparat?',
  'gl': 'Benvido de novo ao universo das linguas. Listo?',
  'be': 'Вітаем зноў у моўным сусвеце. Гатовы?',
  'is': 'Velkominn aftur í tungumálaalheiminn. Tilbúinn?',
  'mt': 'Merħba lura fl-univers tal-lingwi. Lest?',
  // Yeni eklenen karşılamalar
  'pa': 'ਭਾਸ਼ਾ ਬ੍ਰਹਿਮੰਡ ਵਿੱਚ ਵਾਪਸ ਸਵਾਗਤ ਹੈ। ਤਿਆਰ?',
  'ml': 'ഭാഷാ ബ്രഹ്മാണ്ഡത്തിലേക്ക് വീണ്ടും സ്വാഗതം. തയ്യാറ��?',
  'or': 'ଭାଷା ବ୍ରହ୍ମାଣ୍ଡକୁ ପୁନଃ ସ୍ୱାଗତ। ପ୍ରସ୍ତୁତ?',
  'as': 'ভাষাৰ মহাবিশ্বৰলৈ আকৌ স্বাগতম। প্ৰস্তুত?',
  'km': 'សូមស្វាគមន៍ត្រឡប់មកកាន់ចក្រវាលភាសា។ រៀបចំរួចហើយ?',
  'my': 'ဘာသာစကားဗဟုလောကသို့ ပြန်လာခြင်းကို ကြိုဆိုပါသည်။ အဆင်သင့်လား?',
  'lo': 'ຍິນດີຕ້ອນຮັບກັບສູ່ຈັກກະວານພາສາ. ພ້ອມບໍ?',
  'eu': 'Ongi etorri berriro hizkuntzen unibertsora. Prest?',
  'hy': 'Բարի վերադարձ լեզուների տիեզերք։ Պատրա՞ստ ես։',
  'cy': 'Croeso yn ôl i fydysawd yr ieithoedd. Barod?',
  'uz': 'Til olamiga qaytganingga xush kelibsan. Tayyor?',
  'ps': 'بېرته د ژبو کاینات ته ښه راغلې. تیار یې؟',
  'ha': 'Barka da dawowa zuwa sararin harsuna. Shirye kake?',
  'yo': 'Kaabo sí ayé èdè lẹ́ẹ̀kansi. Ṣé ṣetán?',
  'ig': 'Nnọọ azụ na ụwa asụsụ. Ị kwadebere?',
  'so': 'Ku soo dhawoow mar kale caalamka luqadaha. Diyaar miyaa?',
  'zu': 'Uyemukelwa futhi emkhathini wezilimi. Ulungele?',
  'xh': 'Wamkelekile kwakhona kwindalo yeelwimi. Ulungile?',
  'tg': 'Боз ба коиноти забонҳо хуш омадед. Омодаед?',
  'tk': 'Dil älemine gaýdyp geldiň. Taýýar?',
  'ky': 'Тилдер ааламына кайра кош келиңиз. Даярсызбы?',
  // Newly added welcome messages
  'yue': '歡迎返嚟語言宇宙。準備好未？',
  'eo': 'Bonvenon reen al la lingva universo. Pretas?',
  'ht': 'Byenveni tounen nan inivè lang yo. Pare?',
  // Newly added welcome messages (user request)
  'mi': 'Haere mai anō ki te ao reo. Kua rite?',
  'gn': 'Ejujey ñeʼẽ arapýpe. ¿Ikatúpa?',
  'qu': 'Simikuna pachasman kutiy. Listo kachkanki?',
  'om': 'Baga gara unka afaanotaatti deebiʼte. Qophiidhaa?',
  'mg': 'Tongasoa indray eto amin\'ny tontolon\'ny fiteny. Vonona?',
  'rw': 'Murakaza neza kongera mu isanzure ry\'indimi. Witeguye?',
  'rn': 'Urakaze gusubira mu isi y\'indimi. Witeguye?',
  'sn': 'Gamuchirai zvakare munyika yemitauro. Wakagadzirira?',
  'tn': 'O amogetswe gape mo lefatsheng la diteme. O lokile?',
  'dz': 'སྐད་ཡིག་ཀྱི་འཛམ་གླིང་ལ་ལོག་འབྱོར་བཀའ་དྲིན་ཆེ། གྲ་སྒྲིག་ཡོད་མིན?',
  'jv': 'Sugeng rawuh maneh ing jagad basa. Siyap?',
  'gd': 'Fàilte air ais do chruinne nan cànan. Deiseil?',
  'me': 'Dobrodošao nazad u jezički svemir. Spreman?',
};

